ur_admittance_controller:
  joints:
    type: string_array
    default_value: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    description: "UR5e joint names"
    read_only: true
    validation:
      fixed_size<>: [6]

  admittance:
    mass:
      type: double_array
      default_value: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
      description: "Virtual inertia [X,Y,Z,Rx,Ry,Rz] in [kg,kg,kg,kg⋅m²,kg⋅m²,kg⋅m²]"
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.1, 100.0]

    stiffness:
      type: double_array
      default_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      description: "Position stiffness [X,Y,Z,Rx,Ry,Rz] in [N/m,N/m,N/m,Nm/rad,Nm/rad,Nm/rad]"
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 10000.0]

    damping_ratio:
      type: double_array
      default_value: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
      description: "Damping ratios [X,Y,Z,Rx,Ry,Rz]"
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.1, 2.0]

    enabled_axes:
      type: bool_array
      default_value: [true, true, true, true, true, true]
      description: "Enable admittance per axis [X,Y,Z,Rx,Ry,Rz]"
      validation:
        fixed_size<>: [6]

    min_motion_threshold:
      type: double
      default_value: 1.5
      description: "Minimum force/torque to trigger motion [N/Nm]"

    filter_coefficient:
      type: double
      default_value: 0.8
      description: "EMA filter coefficient for F/T sensor (0.1=heavy filtering, 0.95=light filtering)"
      validation:
        bounds<>: [0.05, 0.95]

    drift_reset_threshold:
      type: double
      default_value: 0.001
      description: "Velocity threshold for drift reset [m/s]"

  max_linear_velocity:
    type: double
    default_value: 0.5
    description: "Maximum linear velocity [m/s]"

  max_angular_velocity:
    type: double
    default_value: 1.0
    description: "Maximum angular velocity [rad/s]"

  dynamic_parameters:
    type: bool
    default_value: true
    description: "Enable live parameter tuning"

  world_frame:
    type: string
    default_value: "world"
    description: "World reference frame"

  base_link:
    type: string
    default_value: "base_link"
    description: "Robot base link frame"
    read_only: true

  tip_link:
    type: string
    default_value: "tool0"
    description: "Robot end-effector frame"
    read_only: true

  ft_frame:
    type: string
    default_value: "ft_sensor_link"
    description: "F/T sensor frame"
    read_only: true

# Initial joint configuration for zero-error startup
# These positions place the end-effector at the equilibrium position
initial_joint_positions:
  - 2.137181473386596    # shoulder_pan_joint
  - -1.4998039803657388  # shoulder_lift_joint  
  - 1.549433454173772    # elbow_joint
  - -1.720668606474913   # wrist_1_joint
  - -1.5707963267948966  # wrist_2_joint
  - 0.5664094686907195   # wrist_3_joint

# Equilibrium configuration (desired pose)
equilibrium:
  position: [0.1, 0.4, 0.5]  # meters [x, y, z]
  orientation: [0.0, 0.0, 0.0, 1.0]  # quaternion [x, y, z, w]