ur_admittance_controller:
  joints:
    type: string_array
    default_value: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
    validation:
      fixed_size<>: [6]

  admittance:
    mass:
      type: double_array
      default_value: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.1, 100.0]
    stiffness:
      type: double_array
      default_value: [2.5, 2.5, 2.5, 1.5, 1.5, 1.5]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 10000.0]
    damping:
      type: double_array
      default_value: [30.0, 30.0, 30.0, 30.0, 30.0, 30.0]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 1000.0]
    limits:
      max_angular_acceleration:
        type: double
        default_value: 1.0
        validation:
          bounds<>: [0.1, 10.0]
      max_angular_velocity:
        type: double
        default_value: 1.5
        validation:
          bounds<>: [0.1, 10.0]

  tracking:
    velocity_gain:
      type: double_array
      default_value: [2.0, 2.0, 2.0, 1.0, 1.0, 1.0]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 100.0]
