ur_admittance_controller:
  joints:
    type: string_array
    default_value: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
    description: UR5e joint names
    read_only: true
    validation:
      fixed_size<>: [6]
  admittance:
    mass:
      type: double_array
      default_value: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
      description: Virtual inertia [X,Y,Z,Rx,Ry,Rz] in [kg,kg,kg,kg⋅m²,kg⋅m²,kg⋅m²]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.1, 100.0]
    stiffness:
      type: double_array
      default_value: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
      description: Position stiffness [X,Y,Z,Rx,Ry,Rz] in [N/m,N/m,N/m,Nm/rad,Nm/rad,Nm/rad]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 10000.0]
    damping:
      type: double_array
      default_value: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
      description: Explicit damping values [X,Y,Z,Rx,Ry,Rz] in [Ns/m,Ns/m,Ns/m,Nms/rad,Nms/rad,Nms/rad]
      validation:
        fixed_size<>: [6]
        element_bounds<>: [0.0, 1000.0]
  world_frame:
    type: string
    default_value: world
    description: World reference frame
  base_link:
    type: string
    default_value: base_link
    description: Robot base link frame
    read_only: true
  tip_link:
    type: string
    default_value: p42v_link1
    description: Robot end-effector frame
    read_only: true
  ft_frame:
    type: string
    default_value: ft_frame
    description: F/T sensor frame (from UR description)
    read_only: true