# Complete UR Admittance Controller Configuration
# This is the ONLY config file you need - everything is here!

# System-wide controller manager (optional - uncomment if running full system)
# controller_manager:
#   ros__parameters:
#     update_rate: 1000  # Hz
#     ur_admittance_controller:
#       type: ur_admittance_controller/URAdmittanceController
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#     ft_sensor_broadcaster:
#       type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

# Main controller configuration
ur_admittance_controller:
  joints:
    type: string_array
    default_value: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    description: "List of joint names"

  state_interfaces:
    type: string_array
    default_value: ["position", "velocity"]
    description: "State interface types to claim from hardware"

  # F/T sensor configuration
  ft_sensor_name:
    type: string
    default_value: "wrist_ft_sensor"
    description: "Name of the F/T sensor hardware interface"

  # Add admittance namespace for better organization
  admittance:
    # Pure admittance control parameters
    mass:
      type: double_array
      default_value: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
      description: |
        Virtual inertia matrix diagonal elements [X,Y,Z,Rx,Ry,Rz]
        Units: [kg, kg, kg, kg⋅m², kg⋅m², kg⋅m²]
        Range: (0.1, 100.0] for translations, (0.01, 10.0] for rotations
        Higher values = slower response, more stable
        Lower values = faster response, less stable
      # Comments describing valid ranges instead of validation block
      # Translations: 0.1 to 100.0, Rotations: 0.01 to 10.0

    stiffness:
      type: double_array
      default_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      description: |
        Position stiffness matrix diagonal elements [X,Y,Z,Rx,Ry,Rz]
        Units: [N/m, N/m, N/m, Nm/rad, Nm/rad, Nm/rad]
        Range: [0.0, 2000.0] for translations, [0.0, 200.0] for rotations
        Zero values = pure admittance control (force-to-motion)
        Positive values = impedance control (position+force regulation)
        
        PRESET CONFIGURATIONS:
        Pure Admittance (default): [0, 0, 0, 0, 0, 0]
        Full Impedance: [100, 100, 100, 10, 10, 10]
        XY-Compliant/Z-Stiff: [0, 0, 200, 0, 0, 0]
        Position Control Only: [150, 150, 150, 0, 0, 0]
        
        TUNING GUIDE:
        0 N/m: Pure compliance (no return)
        10-50 N/m: Very soft return
        50-200 N/m: Moderate stiffness
        200-500 N/m: Firm return
        500-2000 N/m: Very stiff
      # Valid range: [0.0, 2000.0] for translations, [0.0, 200.0] for rotations

    damping_ratio:
      type: double_array
      default_value: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
      description: |
        Damping ratio coefficients [X,Y,Z,Rx,Ry,Rz]
        Units: [dimensionless]
        Range: [0.1, 2.0] (typical)
        Values < 1.0: Underdamped (some oscillation, faster response)
        Values = 1.0: Critically damped (no oscillation, optimal response)
        Values > 1.0: Overdamped (no oscillation, slower response)
        Used to compute D matrix based on M and K: D = 2ζ√(MK) if K>0
      # Valid range: 0.0 to 10.0 for all axes

    # Control behavior
    enabled_axes:
      type: bool_array
      default_value: [true, true, true, true, true, true]
      description: |
        Enable/disable admittance control for each axis [X,Y,Z,Rx,Ry,Rz]
        When disabled, the controller will maintain position in that axis
        Common configurations:
        - [true, true, true, false, false, false]: XYZ translation only
        - [false, false, true, false, false, false]: Z-axis (vertical) compliance only
        - [true, true, false, false, false, true]: Horizontal plane + rotation around Z

    min_motion_threshold:
      type: double
      default_value: 1.5
      description: |
        Minimum force/torque magnitude to trigger motion (deadband)
        Units: Newtons (for forces) / Nm (for torques)
        Range: [0.1, 10.0] (typical)
        Smaller values: More sensitive to forces/torques (may detect noise)
        Larger values: Less sensitive (requires more deliberate force)
        Used to filter out sensor noise and unintentional contacts
      # Valid range: 0.01 to 20.0

    filter_coefficient:
      type: double
      default_value: 0.15
      description: |
        Low-pass filter coefficient for wrench signals
        Units: [dimensionless]
        Range: [0.01, 0.9] (typical)
        Formula: filtered = (1-coeff)*previous + coeff*current
        Smaller values: More filtering, smoother motion, more lag
        Larger values: Less filtering, more responsive, may amplify noise
      # Valid range: 0.0 to 1.0

    drift_reset_threshold:
      type: double
      default_value: 0.001
      description: |
        Velocity threshold for position drift prevention
        Units: meters/second
        Range: [0.0001, 0.01] (typical)
        When Cartesian velocity falls below this threshold, the controller
        will automatically update reference position to prevent drift.
        Smaller values: More accurate positioning, may detect noise
        Larger values: Less sensitive, more motion required to reset
      # Valid range: 0.0 to 0.1

  # Cartesian velocity safety limits
  max_linear_velocity:
    type: double
    default_value: 0.5
    description: |
      Maximum linear velocity in Cartesian space
      Units: meters/second
      Range: [0.1, 1.0] (typical, robot-dependent)
      Critical safety parameter that limits the maximum translational
      velocity regardless of external forces. Should be set based on
      workspace constraints and safety requirements.
    # Valid range: 0.01 to 2.0

  max_angular_velocity:
    type: double
    default_value: 1.0
    description: |
      Maximum angular velocity in Cartesian space
      Units: radians/second
      Range: [0.2, 2.0] (typical, robot-dependent)
      Critical safety parameter that limits the maximum rotational
      velocity regardless of external torques. Should be set based on
      workspace constraints and safety requirements.
    # Valid range: 0.01 to 3.14 rad/s

  dynamic_parameters:
    type: bool
    default_value: true
    description: "Enable live parameter tuning"

  # Frame configuration
  world_frame:
    type: string
    default_value: "world"
    description: "World reference frame"

  base_link:
    type: string
    default_value: "base_link"
    description: "Robot base link frame"

  tip_link:
    type: string
    default_value: "tool0"
    description: "Robot end-effector frame"

  ft_frame:
    type: string
    default_value: "tool0"
    description: "F/T sensor frame"

  # Joint limits
  joint_limits_position_min:
    type: double_array
    default_value: [-6.283, -6.283, -3.142, -6.283, -6.283, -6.283]
    description: "Minimum joint position limits (radians)"
    
  joint_limits_position_max:
    type: double_array
    default_value: [6.283, 6.283, 3.142, 6.283, 6.283, 6.283]
    description: "Maximum joint position limits (radians)"
    
  joint_limits_velocity_max:
    type: double_array
    default_value: [3.14, 3.14, 3.14, 6.28, 6.28, 6.28]
    description: "Maximum joint velocity limits (rad/s)"

  # Kinematics plugin
  kinematics_plugin_package:
    type: string
    default_value: "ur_kinematics"
    description: "Package containing the kinematics plugin"

  kinematics_plugin_name:
    type: string
    default_value: "ur_kinematics/URKinematicsPlugin"
    description: "Name of the kinematics plugin to use"

# ==============================================================================
# EXAMPLE CONFIGURATIONS - Copy these values to override defaults above
# ==============================================================================

# PRESET 1: Pure Admittance (Default) - No position return, pure force control
# admittance:
#   stiffness: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#   mass: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
#   damping_ratio: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]

# PRESET 2: Soft Impedance - Gentle position return
# admittance:
#   stiffness: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
#   mass: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
#   damping_ratio: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]

# PRESET 3: Stiff Z-axis - Compliant X/Y, rigid vertical (assembly tasks)
# admittance:
#   stiffness: [0.0, 0.0, 200.0, 0.0, 0.0, 0.0]
#   mass: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
#   damping_ratio: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]

# PRESET 4: Conservative Startup - Safe parameters for initial testing
# max_linear_velocity: 0.3      # m/s (reduced from default 0.5)
# max_angular_velocity: 0.8     # rad/s (reduced from default 1.0)
# admittance:
#   mass: [12.0, 12.0, 12.0, 1.2, 1.2, 1.2]  # Higher mass for stability
#   damping_ratio: [1.2, 1.2, 1.2, 1.2, 1.2, 1.2]  # Higher damping
#   min_motion_threshold: 3.0  # More intentional force required