ur_admittance_controller:
  joints:
    type: string_array
    default_value: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    description: "List of joint names"

  sensor_interface:
    topic_config:
      topic_name:
        type: string
        default_value: "/wrist_ft_sensor"
        description: "Force/torque sensor topic name"
      
      data_timeout_ms:
        type: double
        default_value: 50.0
        description: "Maximum age of sensor data before considered stale (ms)"
      
      frame_id_override:
        type: string
        default_value: ""
        description: "Override frame_id from topic (empty = use topic's frame)"
      
      enable_transform_caching:
        type: bool
        default_value: true
        description: "Cache transforms in non-RT callback"

  fallback_strategy:
    on_stale_data:
      type: string
      default_value: "hold_position"
      description: "Action on stale data: 'hold_position', 'use_last', 'zero_force'"
      validation:
        one_of<>: [["hold_position", "use_last", "zero_force"]]
    
    max_missed_updates:
      type: int
      default_value: 10
      description: "Maximum consecutive missed updates before safety stop"

  admittance:
    mass:
      type: double_array
      default_value: [8.0, 8.0, 8.0, 0.8, 0.8, 0.8]
      description: |
        Virtual inertia matrix diagonal elements [X,Y,Z,Rx,Ry,Rz]
        Units: [kg, kg, kg, kg⋅m², kg⋅m², kg⋅m²]
        Range: (0.1, 100.0] for translations, (0.01, 10.0] for rotations
        Higher values = slower response, more stable
        Lower values = faster response, less stable

    stiffness:
      type: double_array
      default_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      description: |
        Position stiffness matrix diagonal elements [X,Y,Z,Rx,Ry,Rz]
        Units: [N/m, N/m, N/m, Nm/rad, Nm/rad, Nm/rad]
        Range: [0.0, 2000.0] for translations, [0.0, 200.0] for rotations
        Zero values = pure admittance control (force-to-motion)
        Positive values = impedance control (position+force regulation)
        
        PRESET CONFIGURATIONS:
        Pure Admittance (default): [0, 0, 0, 0, 0, 0]
        Full Impedance: [100, 100, 100, 10, 10, 10]
        XY-Compliant/Z-Stiff: [0, 0, 200, 0, 0, 0]
        Position Control Only: [150, 150, 150, 0, 0, 0]
        
        TUNING GUIDE:
        0 N/m: Pure compliance (no return)
        10-50 N/m: Very soft return
        50-200 N/m: Moderate stiffness
        200-500 N/m: Firm return
        500-2000 N/m: Very stiff

    damping_ratio:
      type: double_array
      default_value: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
      description: |
        Damping ratio coefficients [X,Y,Z,Rx,Ry,Rz]
        Units: [dimensionless]
        Range: [0.1, 2.0] (typical)
        Values < 1.0: Underdamped (some oscillation, faster response)
        Values = 1.0: Critically damped (no oscillation, optimal response)
        Values > 1.0: Overdamped (no oscillation, slower response)
        Used to compute D matrix based on M and K: D = 2ζ√(MK) if K>0

    enabled_axes:
      type: bool_array
      default_value: [true, true, true, true, true, true]
      description: |
        Enable/disable admittance control for each axis [X,Y,Z,Rx,Ry,Rz]
        When disabled, the controller will maintain position in that axis
        Common configurations:
        - [true, true, true, false, false, false]: XYZ translation only
        - [false, false, true, false, false, false]: Z-axis (vertical) compliance only
        - [true, true, false, false, false, true]: Horizontal plane + rotation around Z

    min_motion_threshold:
      type: double
      default_value: 1.5
      description: |
        Minimum force/torque magnitude to trigger motion (deadband)
        Units: Newtons (for forces) / Nm (for torques)
        Range: [0.1, 10.0] (typical)
        Smaller values: More sensitive to forces/torques (may detect noise)
        Larger values: Less sensitive (requires more deliberate force)
        Used to filter out sensor noise and unintentional contacts

    filter_coefficient:
      type: double
      default_value: 0.15
      description: |
        Low-pass filter coefficient for wrench signals
        Units: [dimensionless]
        Range: [0.01, 0.9] (typical)
        Formula: filtered = (1-coeff)*previous + coeff*current
        Smaller values: More filtering, smoother motion, more lag
        Larger values: Less filtering, more responsive, may amplify noise

    drift_reset_threshold:
      type: double
      default_value: 0.001
      description: |
        Velocity threshold for position drift prevention
        Units: meters/second
        Range: [0.0001, 0.01] (typical)
        When Cartesian velocity falls below this threshold, the controller
        will automatically update reference position to prevent drift.
        Smaller values: More accurate positioning, may detect noise
        Larger values: Less sensitive, more motion required to reset

  max_linear_velocity:
    type: double
    default_value: 0.5
    description: |
      Maximum linear velocity in Cartesian space
      Units: meters/second
      Range: [0.1, 1.0] (typical, robot-dependent)
      Critical safety parameter that limits the maximum translational
      velocity regardless of external forces. Should be set based on
      workspace constraints and safety requirements.

  max_angular_velocity:
    type: double
    default_value: 1.0
    description: |
      Maximum angular velocity in Cartesian space
      Units: radians/second
      Range: [0.2, 2.0] (typical, robot-dependent)
      Critical safety parameter that limits the maximum rotational
      velocity regardless of external torques. Should be set based on
      workspace constraints and safety requirements.

  dynamic_parameters:
    type: bool
    default_value: true
    description: "Enable live parameter tuning"

  world_frame:
    type: string
    default_value: "world"
    description: "World reference frame"

  base_link:
    type: string
    default_value: "base_link"
    description: "Robot base link frame"

  tip_link:
    type: string
    default_value: "tool0"
    description: "Robot end-effector frame"

  ft_frame:
    type: string
    default_value: "ft_sensor_link"
    description: "F/T sensor frame"

  kinematics_plugin_package:
    type: string
    default_value: "kinematics_interface"
    description: "Package containing the kinematics plugin"

  kinematics_plugin_name:
    type: string
    default_value: "kinematics_interface_kdl/KinematicsInterfaceKDL"
    description: "Name of the kinematics plugin to use"


