force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: "tcp_fts_sensor"
    state_interface_names:
      - "tcp_fts_sensor/force.x"
      - "tcp_fts_sensor/force.y"
      - "tcp_fts_sensor/force.z"
      - "tcp_fts_sensor/torque.x"
      - "tcp_fts_sensor/torque.y"
      - "tcp_fts_sensor/torque.z"
    frame_id: "tool0"
    topic_name: "ft_sensor_readings"