controller_manager:
  ros__parameters:
    update_rate: 500  # Hz - Higher rate for real hardware
    
ur_admittance_controller:
  ros__parameters:
    type: ur_admittance_controller/AdmittanceController
    # F/T sensor configuration for hardware
    ft_sensor_name: "tcp_fts_sensor"  # Override default for hardware mode
    ft_frame: "tcp_fts_sensor"  # Frame ID for real hardware F/T sensor
    sensor_interface.mode: "hardware"  # Use hardware interfaces for real robot
    fallback_strategy.on_stale_data: "hold_position"
    fallback_strategy.max_missed_updates: 5  # Stricter for real robot
    # Additional parameters loaded from admittance_config.yaml by generate_parameter_library