controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
ur_admittance_controller:
  ros__parameters:
    type: ur_admittance_controller/AdmittanceController
    # F/T sensor interface configuration for simulation
    ft_frame: "ft_sensor_link"  # Frame ID used by ur_simulation_gz
    sensor_interface.mode: "topic"  # Use topic mode for simulation
    sensor_interface.topic_config.topic_name: "/wrist_ft_sensor"
    sensor_interface.topic_config.data_timeout_ms: 100.0
    sensor_interface.topic_config.enable_transform_caching: true
    sensor_interface.topic_config.frame_id_override: ""  # Use frame from topic
    fallback_strategy.on_stale_data: "hold_position"
    fallback_strategy.max_missed_updates: 10
    # Additional parameters loaded from admittance_config.yaml by generate_parameter_library